name: Publish UX Capture NPM modules
on:
  push:
    branches:
      - github-actions-npm-publish
jobs:
  Publish-NPM-modules:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

      - run: echo "🍏 This job's status is ${{ job.status }}."
      # - name: Run lerna to publish NPM packages
      #   run: yarn deploy
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
